### ISSUE TITLE
Compatibility to aws-cdk v2.56+

### ISSUE THREAD

**Issue by pfried** [cdklabs/awscdk-appsync-utils#8]
I really liked the CodeFirst approach which allows us to do certain things which is not easily possible with a schema file.

As this library was separated from the appsync package per this [PR](https://github.com/aws/aws-cdk/pull/23250) I find myself in a situation where the library is not in sync anymore with the CDK constructs.

The package does not seem to be released with the rest of the CDK packages anymore. The package.json shows a dependency for aws cdk v 2.55.1 [here](https://github.com/cdklabs/awscdk-appsync-utils/blob/main/package.json#L67) without a semver range.

How is the future of this package planned? Can it be re-integrated with the aws-cdk releases?

Best 
Friedrich

**Comment by MrArnoldPalmer** [comment]
So since you can't express semver ranges across multiple pre-release versions of a package as far as I can tell, we will have to release as new versions of the appsync alpha package are released. I can figure out how to include cdk dependencies in our automated package upgrades as part of the projen workflows and then it should all happen automatically.

**Comment by MrArnoldPalmer** [comment]
Since the appsync module is now stable, taking a peerDependency on aws-cdk-lib ^2.60.0 allows users to depend on newer versions as needed.

**Comment by pfried** [comment]
Thanks for that, do you have a timeline for the merge of the open pull request? Is there any blocker I can help with?
